language: node_js
node_js:
  - 'stable'

sudo: required
addons:
  chrome: stable
  hostname: localhost

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: build
  on:
    branch:
      - HW8SEM2
      - master
      - devel
      - FinishingLastSem
