export default {
	// Counter
	INCREMENT_COUNTER: 'INCREMENT_COUNTER',
	DECREMENT_COUNTER: 'DECREMENT_COUNTER',

	UPDATE_CHATS: 'UPDATE_CHAT',
	UPDATE_MESSAGES: 'UPDATE_MESSAGES',
	INVALIDATE_APP_DATA: 'INVALIDATE_APP_DATA',

	UPDATE_PROFILE: 'UPDATE_PROFILE',
	INVALIDATE_PROFILE: 'INVALIDATE_PROFILE',

	UPDATE_APP_STATE: 'UPDATE_APP_STATE',

	POLL_START: 'POLL_START',
	POLL_STOP: 'POLL_STOP',
};
